# Default values for helmv2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

productionSlot: blue
blue:
  enabled: true
  tag: latest

green:
  enabled: false
  tag: latest

replicaCount: 2
repository:
  image: openhackefq8acr.azurecr.io/devopsoh/api-poi
  pullPolicy: Always
image:
  name: mydrive-poi
  label: mydrive-poi
  containerPort: 8080
service:
  externalPort: 80
ingress:
  enabled: true
  annotations:
#    kubernetes.io/ingress.class: traefik
    kubernetes.io/ingress.class: addon-http-application-routing
  rules:
    endpoint:
      host: prod.d77ec743aa78470a8356.westus.aksapp.io
      paths:
      - path: /
        serviceName: poi-service-prod
        servicePort: 80
    endpoint2:
      host: test.d77ec743aa78470a8356.westus.aksapp.io
      paths:
      - path: /
        serviceName: poi-service-stage
        servicePort: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
